/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const JobType = IDL.Variant({
  'repair' : IDL.Null,
  'inspection' : IDL.Null,
  'emergency' : IDL.Null,
  'replacement' : IDL.Null,
});
export const Lead = IDL.Record({
  'id' : IDL.Nat,
  'postcode' : IDL.Text,
  'jobType' : JobType,
  'name' : IDL.Text,
  'createdAt' : IDL.Int,
  'email' : IDL.Text,
  'message' : IDL.Opt(IDL.Text),
  'phone' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'getAllLeads' : IDL.Func([], [IDL.Vec(Lead)], ['query']),
  'getAllLeadsPublic' : IDL.Func([], [IDL.Vec(Lead)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'submitLead' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, JobType, IDL.Opt(IDL.Text)],
      [Lead],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const JobType = IDL.Variant({
    'repair' : IDL.Null,
    'inspection' : IDL.Null,
    'emergency' : IDL.Null,
    'replacement' : IDL.Null,
  });
  const Lead = IDL.Record({
    'id' : IDL.Nat,
    'postcode' : IDL.Text,
    'jobType' : JobType,
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
    'email' : IDL.Text,
    'message' : IDL.Opt(IDL.Text),
    'phone' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'getAllLeads' : IDL.Func([], [IDL.Vec(Lead)], ['query']),
    'getAllLeadsPublic' : IDL.Func([], [IDL.Vec(Lead)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'submitLead' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, JobType, IDL.Opt(IDL.Text)],
        [Lead],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };